### ISSUE TITLE
Olomouc nelze přidat.

### ISSUE THREAD

**Issue by brebtatv** [dvejsada/Air_Quality_CZ#4]
Olomouc nelze přidat, nemá entity.
Vlastní stanici vidím a nějaká data včetně indexu má.
https://www.chmi.cz/files/portal/docs/uoco/web_generator/aqindex_slide3h2/mp_MOLSA_CZ.html

![Screenshot_20240407_074553_Home Assistant](https://github.com/dvejsada/Air_Quality_CZ/assets/10747062/940f960b-bcc2-4be8-ad36-5f6ba3522586)

**Comment by brebtatv** [comment]
Koukám, že v JSON jsou taky vidět.
![Screenshot_20240407_075136_Chrome](https://github.com/dvejsada/Air_Quality_CZ/assets/10747062/2a6fa48a-7cc4-4be8-bac2-9053d7ec091b)

**Comment by brebtatv** [comment]
Problém souvisí se seznamem stanic v souboru "const.py", pokud ručně přidám vybranou stanici, vidím relevantní entity.

**Comment by dvejsada** [comment]
Doplněno, jsou tam 2 stanice v Olomouci, je třeba vybrat ze seznamu - doplním tam ještě kontrolu validity názvu stanice při konfiguraci (bohužel HA selector defaultně umožňuje vepsat i vlastní hodnotu v rámci poskytnutého seznamu).
