### ISSUE TITLE
Brno

### ISSUE THREAD

**Issue by rkotulan** [dvejsada/Air_Quality_CZ#5]
V nabídce měřících stanic nevidím Brno.
Existuje více oblastí v https://www.[chmi.cz/files/portal/docs/uoco/web_generator/aqindex_3h_cze.json](https://www.chmi.cz/files/portal/docs/uoco/web_generator/aqindex_3h_cze.json)

![image](https://github.com/dvejsada/Air_Quality_CZ/assets/18562096/6b675be6-9d58-4cf7-9874-bcab150d0e00)

**Comment by brebtatv** [comment]
Problém souvisí se seznamem stanic v souboru "const.py", pokud ručně přidám vybranou stanici, vidím relevantní entity.

Viz https://github.com/dvejsada/Air_Quality_CZ/issues/4

**Comment by dvejsada** [comment]
Vyřešeno, prosím updatujte na v0.1.1.

Díky za upozorenění!
